# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-restore --no-build --verbosity normal -c Release
    - name: Pack
      run: dotnet pack --no-restore --no-build -c Release -o ./package
    - name: Set package version
      run: PKG_VERSION=$(sed -n 's:.*<Version>\(.*\)</Version>.*:\1:p' ./src/FoSouzaDev.Common.Domain/FoSouzaDev.Common.Domain.csproj); echo 'PKG_VERSION=$PKG_VERSION' >> $GITHUB_ENV
    - name: Publish in nuget.org
      run: dotnet nuget push ./package/FoSouzaDev.Common.Domain.$PKG_VERSION.nupkg --api-key ${{ secrets.NUGETORG }} --source https://api.nuget.org/v3/index.json